# Generated by Django 4.1.5 on 2023-02-26 14:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("created_time", models.DateTimeField(editable=False)),
                ("customer", models.PositiveBigIntegerField()),
                (
                    "customer_sub_type",
                    models.CharField(
                        choices=[
                            ("BUSINESS", "Business"),
                            ("INDIVIDUAL", "Individual"),
                        ],
                        default="BUSINESS",
                        max_length=30,
                    ),
                ),
                ("taxable", models.BooleanField(default=True)),
                ("customer_name", models.CharField(max_length=30)),
                ("shipping_address", models.CharField(max_length=30)),
                ("shipping_address_line_2", models.CharField(max_length=30, null=True)),
                ("shipping_city", models.CharField(max_length=30)),
                ("shipping_state", models.CharField(max_length=30)),
                ("shipping_code", models.PositiveSmallIntegerField()),
                ("assigned_sales_person", models.CharField(max_length=30)),
                ("state_manager", models.CharField(max_length=30)),
                ("business_ein", models.CharField(max_length=30)),
                ("tobacco_license", models.CharField(max_length=30)),
                ("parent_chain", models.CharField(max_length=30)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("CHAIN", "Chain"),
                            ("CONSUMER", "Consumer"),
                            ("DISTRIBUTOR", "Distributor"),
                            ("INDEPENDENT_STORE", "Independent Store"),
                        ],
                        default="",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("customer_pays_vape_tax", models.BooleanField(null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("invoice", models.PositiveBigIntegerField()),
                ("invoice_number", models.CharField(max_length=30)),
                ("invoice_level_tax_authority", models.CharField(max_length=30)),
                ("invoice_date", models.DateField()),
                ("invoice_status", models.CharField(max_length=30)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="magdataapp.customer",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("product", models.PositiveBigIntegerField()),
                ("sku", models.CharField(max_length=30, unique=True)),
                ("item_name", models.CharField(max_length=100)),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("preferred_vendor", models.CharField(max_length=30)),
                ("stock_on_hand", models.PositiveSmallIntegerField()),
                ("category_name", models.CharField(max_length=30)),
                ("e_liquid_ml", models.FloatField()),
                ("msrp", models.DecimalField(decimal_places=2, max_digits=7)),
                ("reporting_sub_category", models.CharField(max_length=30)),
                ("reporting_category_primary", models.CharField(max_length=30)),
                ("reporting_category_cannabinoid", models.CharField(max_length=30)),
                ("cloud8_b2c", models.BooleanField()),
                (
                    "b2c_msrp",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                ("retail_units_in_wholesale", models.PositiveSmallIntegerField()),
                (
                    "OH_otp_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "PA_otp_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "WV_otp_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice_Line_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("item_total", models.DecimalField(decimal_places=2, max_digits=7)),
                ("taxes_amount", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="magdataapp.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="magdataapp.item",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
